#!/usr/bin/env python3

"""
 One way directory Synchronizer.

This makes me disciplined to stick with one directory.
"""


def scanner():
    return True


def last_modified():
    return True


def file_size():
    return True


def sync():
    return True


def main():
    return True
